import { BookCourse, CitationSource, KnowledgeNode, LessonInfo, TranscriptEntry } from "@/types/tutor";

export const MOCK_BOOKS: BookCourse[] = [
  {
    id: "cs-dsa-01",
    title: "Data Structures & Algorithm Analysis",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    edition: "4th Edition · MIT Press",
    pageCount: 412,
    chunkCount: 1840,
    conceptCount: 87,
    indexed: true,
    lastStudied: "Today, 14:20",
    coverGradient: ["#0f2b48", "#081326"],
    topics: [
      "Dynamic Arrays & amortized analysis",
      "Singly and Doubly Linked Lists",
      "Binary Search Trees & Balancing",
      "Graph Traversal (BFS / DFS)",
      "Dynamic Programming memoization",
      "Hash Map collision resolution",
    ],
  },
  {
    id: "cs-ml-02",
    title: "Pattern Recognition & Machine Learning",
    author: "Christopher M. Bishop",
    edition: "Information Science Series",
    pageCount: 738,
    chunkCount: 3120,
    conceptCount: 142,
    indexed: true,
    lastStudied: "Yesterday",
    coverGradient: ["#1e1b4b", "#09091b"],
    topics: [
      "Probability Distributions & Bayesian Inference",
      "Linear Models for Regression",
      "Neural Network Backpropagation",
      "Kernel Methods & Support Vector Machines",
      "Variational Inference & Latent Variables",
    ],
  },
  {
    id: "phys-qc-03",
    title: "Quantum Computation and Quantum Information",
    author: "Michael A. Nielsen, Isaac L. Chuang",
    edition: "Cambridge University Press",
    pageCount: 676,
    chunkCount: 2890,
    conceptCount: 118,
    indexed: true,
    lastStudied: "3 days ago",
    coverGradient: ["#162838", "#08151f"],
    topics: [
      "Qubit States & Bloch Sphere Representation",
      "Quantum Gates and Unitary Transformations",
      "Quantum Fourier Transform",
      "Bell Inequalities & Entanglement",
    ],
  },
];

export const MOCK_KNOWLEDGE_NODES: KnowledgeNode[] = [
  {
    id: "node-ll-core",
    label: "Node Architecture",
    chapter: "Chapter 04",
    page: 142,
    position: [0, 0.4, 0],
    status: "active",
    relevanceScore: 0.98,
    category: "concept",
  },
  {
    id: "node-dyn-mem",
    label: "Dynamic Memory",
    chapter: "Chapter 04",
    page: 144,
    position: [-1.8, 0.9, -0.6],
    status: "retrieved",
    relevanceScore: 0.94,
    category: "concept",
  },
  {
    id: "node-ptrs",
    label: "Pointer Manipulation",
    chapter: "Chapter 04",
    page: 146,
    position: [1.9, 0.7, -0.5],
    status: "retrieved",
    relevanceScore: 0.91,
    category: "algorithm",
  },
  {
    id: "node-insert",
    label: "Head & Tail Insertion",
    chapter: "Chapter 04",
    page: 149,
    position: [-1.5, -0.9, 0.8],
    status: "idle",
    relevanceScore: 0.86,
    category: "algorithm",
  },
  {
    id: "node-traversal",
    label: "Traversal & Search",
    chapter: "Chapter 04",
    page: 153,
    position: [1.7, -0.8, 0.9],
    status: "idle",
    relevanceScore: 0.82,
    category: "algorithm",
  },
  {
    id: "node-doubly",
    label: "Doubly Linked Structures",
    chapter: "Chapter 04",
    page: 158,
    position: [0.2, 1.9, -1.2],
    status: "idle",
    relevanceScore: 0.75,
    category: "concept",
  },
  {
    id: "node-cache",
    label: "Cache Locality Tradeoffs",
    chapter: "Chapter 04",
    page: 161,
    position: [-0.4, -1.8, -1.1],
    status: "idle",
    relevanceScore: 0.79,
    category: "reference",
  },
];

export const MOCK_CITATIONS: CitationSource[] = [
  {
    id: "cite-142",
    bookTitle: "Data Structures & Algorithm Analysis",
    author: "Thomas H. Cormen",
    chapterNumber: 4,
    chapterTitle: "Linked Lists & Elementary Structures",
    pageNumber: 142,
    section: "4.1 The Anatomy of a Singly-Linked Node",
    excerpt:
      "A linked list consists of discrete nodes allocated arbitrarily throughout heap memory. Unlike a contiguous array, each node encapsulates two fundamental primitives: the payload data element, and a reference pointer addressing the succeeding node. This decouple eliminates rigid buffer constraints at the cost of pointer overhead.",
    retrievalReason: "Linked List → Node Anatomy → Dynamic Heap Allocation",
    relevanceScore: 0.984,
    nodeId: "node-ll-core",
  },
  {
    id: "cite-144",
    bookTitle: "Data Structures & Algorithm Analysis",
    author: "Thomas H. Cormen",
    chapterNumber: 4,
    chapterTitle: "Linked Lists & Elementary Structures",
    pageNumber: 144,
    section: "4.2 Dynamic Memory vs. Contiguous Arrays",
    excerpt:
      "When comparing an array with a linked structure, the critical tradeoff lies in CPU cache locality versus insertion flexibility. Arrays yield O(1) random access due to predictable stride strides across the L1 cache, whereas linked nodes require pointer dereferencing that can incur memory stalls.",
    retrievalReason: "Array Comparison → Cache Locality → Pointer Indirection",
    relevanceScore: 0.942,
    nodeId: "node-dyn-mem",
  },
  {
    id: "cite-146",
    bookTitle: "Data Structures & Algorithm Analysis",
    author: "Thomas H. Cormen",
    chapterNumber: 4,
    chapterTitle: "Linked Lists & Elementary Structures",
    pageNumber: 146,
    section: "4.3 Pointer Manipulation & Memory Invariants",
    excerpt:
      "Inserting into the head of a linked list is strictly an O(1) operation: the new node's next pointer is assigned to the current head, followed by updating the head reference. No element relocation occurs, completely avoiding the O(N) array resize penalty.",
    retrievalReason: "Insertion Complexity → Pointer Mutation → O(1) Invariant",
    relevanceScore: 0.915,
    nodeId: "node-ptrs",
  },
];

export const INITIAL_LESSON: LessonInfo = {
  courseTitle: "DATA STRUCTURES & ALGORITHMS",
  courseCode: "CS-204",
  chapterNumber: 4,
  chapterTitle: "LINKED LISTS",
  lessonIndex: 3,
  totalLessons: 8,
  topicTitle: "Introduction to Node Architecture",
  progressPercent: 38,
  concepts: [
    {
      id: "c1",
      title: "Contiguous vs. Non-contiguous Memory",
      completed: true,
      active: false,
      summary: "Understanding how the OS heap manages non-sequential allocations.",
    },
    {
      id: "c2",
      title: "Data Payload and Next-Pointer Structure",
      completed: true,
      active: false,
      summary: "Examining memory layout of single node struct.",
    },
    {
      id: "c3",
      title: "Node Architecture & Pointer Indirection",
      completed: false,
      active: true,
      summary: "How pointer chains establish relational order without physical adjacency.",
    },
    {
      id: "c4",
      title: "O(1) Head Insertion Mechanism",
      completed: false,
      active: false,
      summary: "Step-by-step pointer reassignment without data copying.",
    },
    {
      id: "c5",
      title: "Tail Pointers and Boundary Invariants",
      completed: false,
      active: false,
      summary: "Managing edge cases when referencing nullptr or empty lists.",
    },
  ],
};

export const INITIAL_TRANSCRIPT: TranscriptEntry[] = [
  {
    id: "t1",
    role: "ai",
    text: "Welcome back. Today we are diving into Chapter 4 of Cormen. Before we discuss insertion or deletion algorithms, we first need to understand what a node actually represents inside physical system memory.",
    timestamp: "14:22",
    sourceCitationId: "cite-142",
  },
  {
    id: "t2",
    role: "user",
    text: "Hocam, why can't we simply use a dynamic array here? Why do we need individual nodes?",
    timestamp: "14:23",
  },
  {
    id: "t3",
    role: "ai",
    text: "That is the foundational question of computer architecture. Think about how an array lives: it requires a continuous, contiguous block of RAM. When your array expands past capacity, the runtime must allocate an entirely new block and copy every single element over. A node frees us from that contiguous lock.",
    timestamp: "14:23",
    sourceCitationId: "cite-144",
  },
];

